[tg_api]
    token = '...' # BotFather helps

[notion_api]
    token = '...' # notion integrations
    timeout = '10s'
    version = '2021-08-16'
    db_id = '...' # ID of DB in notion
    search_url = 'https://api.notion.com/v1/search'
    update_interval = '45m'
